--- name:default
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0

# Visual Odometry Stereo parameters. Including intrinsic and extrinsic camera calibration parameters among othersfor a full parameter list have a look at viso2Types.hpp and at viso_stereo.h of the viso2 library
viso2_parameters:
  ransac_iters: 200 #number of RANSAC iterations
  inlier_threshold: 1.5 #fundamental matrix inlier threshold
  reweighting: true #lower border weights (more robust to calibration errors)
  match:
    nms_n: 3 #non-max-suppression: min. distance between maxima (in pixels)
    nms_tau: 50 #non-max-suppression: interest point peakiness threshold
    match_binsize: 50 #matching bin width/height (affects efficiency only) Step size for matching features (forward/backward and right/left)
    match_radius: 200 #matching radius (du/dv in pixels)
    match_disp_tolerance: 1 #dv tolerance for stereo matches (in pixels)
    outlier_disp_tolerance: 5 #outlier removal: disparity tolerance (in pixels)
    outlier_flow_tolerance: 5 #outlier removal: flow tolerance (in pixels)
    multi_stage: 1 #0=disabled,1=multistage matching (denser and faster)
    half_resolution: 1 #0=disabled,1=match at half resolution, refine at full resolution
    refinement: 2 #refinement (0=none,1=pixel,2=subpixel)
  bucket:
    max_features: 2 #maximal number of features per bucket
    bucket_width: 10.0 #width of bucket
    bucket_height: 10.0 #height of bucket
# Set to true if output debug information is desirable.
output_debug: true
--- name:sherpa
# maximum latency, in seconds, of the stream aligner. The aligner will start
# dropping samples if the difference between the last output and last input is
# greater than this
aggregator_max_latency: 0.3
# minimum time, in s, between two sequential samples arrive on left_frame
left_frame_period: 0.01
# minimum time, in s, between two sequential samples arrive on right_frame
right_frame_period: 0.01
# Calibration parameter for the frame_helper
calib_parameters:
  camLeft:
    fx: 1295.19657
    fy: 1301.96551
    cx: 704.77750
    cy: 511.01565
    d0: -0.18141
    d1: 0.14513
    d2: -0.00446
    d3: 0.00323
    width: 1360
    height: 1024
  camRight:
    fx: 1293.69356
    fy: 1296.17046
    cx: 703.42133
    cy: 516.26349
    d0: -0.16958
    d1: 0.10206
    d2: 0.00253
    d3: 0.00048
    width: 1360
    height: 1024
  extrinsic:
    tx: -172.23694
    ty: 2.35985
    tz: -2.44105
    rx: 0.02316
    ry: 0.00714
    rz: -0.00807
--- name:bumblebee
# maximum latency, in seconds, of the stream aligner. The aligner will start
# dropping samples if the difference between the last output and last input is
# greater than this
aggregator_max_latency: 0.1
# minimum time, in s, between two sequential samples arrive on left_frame
left_frame_period: 0.05
# minimum time, in s, between two sequential samples arrive on right_frame
right_frame_period: 0.05

# Calibration parameter for the frame_helper
calib_parameters:
  camLeft:
    fx: 837.98636
    fy: 838.56569
    cx: 509.74846
    cy: 376.99711
    d0: -0.35914
    d1: 0.16317
    d2: 0.00039
    d3: 0.00041
    pixel_error:
        data:
        - 0.06887
        - 0.08192
    width: 1024
    height: 768
  camRight:
    fx: 837.40801
    fy: 838.06473
    cx: 536.53701
    cy: 377.66591
    d0: -0.35499
    d1: 0.15218
    d2: 0.00019
    d3: -0.00016
    pixel_error:
        data:
        - 0.07723
        - 0.08236
    width: 1024
    height: 768
#Distnace between left and right camera
  extrinsic:
    tx: 120.42814 #baseline in x (mm)
    ty: 0.63857 #baseline in y (mm)
    tz: 0.3051 #baseline in z (mm)
    rx: 0.00125 #rotation along x (rad)
    ry: -0.00333 #rotation along y (rad)
    rz: 0.00542 #rotation along z (rad)


