--- name:default
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0

# Visual Odometry Stereo parameters. Including intrinsic and extrinsic camera calibration parameters among othersfor a full parameter list have a look at viso2Types.hpp and at viso_stereo.h of the viso2 library
viso2_parameters:
  ransac_iters: 200 #number of RANSAC iterations
  inlier_threshold: 1.5 #fundamental matrix inlier threshold
  reweighting: true #lower border weights (more robust to calibration errors)
  match:
    nms_n: 3 #non-max-suppression: min. distance between maxima (in pixels)
    nms_tau: 50 #non-max-suppression: interest point peakiness threshold
    match_binsize: 50 #matching bin width/height (affects efficiency only)
    match_radius: 200 #matching radius (du/dv in pixels)
    match_disp_tolerance: 8 #dv tolerance for stereo matches (in pixels)
    outlier_disp_tolerance: 5 #outlier removal: disparity tolerance (in pixels)
    outlier_flow_tolerance: 5 #outlier removal: flow tolerance (in pixels)
    multi_stage: 1 #0=disabled,1=multistage matching (denser and faster)
    half_resolution: 1 #0=disabled,1=match at half resolution, refine at full resolution
    refinement: 1 #refinement (0=none,1=pixel,2=subpixel)
  bucket:
    max_features: 5 #maximal number of features per bucket
    bucket_width: 20.0 #width of bucket
    bucket_height: 20.0 #height of bucket
--- name:sherpa
# maximum latency, in seconds, of the stream aligner. The aligner will start
# dropping samples if the difference between the last output and last input is
# greater than this
aggregator_max_latency: 0.3
# minimum time, in s, between two sequential samples arrive on left_frame
left_frame_period: 0.01
# minimum time, in s, between two sequential samples arrive on right_frame
right_frame_period: 0.01
# Calibration parameter for the frame_helper
calib_parameters:
  camLeft:
    fx: 1295.19657
    fy: 1301.96551
    cx: 704.77750
    cy: 511.01565
    d0: -0.18141
    d1: 0.14513
    d2: -0.00446
    d3: 0.00323
    width: 1360
    height: 1024
  camRight:
    fx: 1293.69356
    fy: 1296.17046
    cx: 703.42133
    cy: 516.26349
    d0: -0.16958
    d1: 0.10206
    d2: 0.00253
    d3: 0.00048
    width: 1360
    height: 1024
  extrinsic:
    tx: -172.23694
    ty: 2.35985
    tz: -2.44105
    rx: 0.02316
    ry: 0.00714
    rz: -0.00807
--- name:bumblebee
# maximum latency, in seconds, of the stream aligner. The aligner will start
# dropping samples if the difference between the last output and last input is
# greater than this
aggregator_max_latency: 0.3
# minimum time, in s, between two sequential samples arrive on left_frame
left_frame_period: 0.06
# minimum time, in s, between two sequential samples arrive on right_frame
right_frame_period: 0.06

# Calibration parameter for the frame_helper
calib_parameters:
  camLeft:
    fx: 868.51003
    fy: 866.87998
    cx: 524.58520
    cy: 377.92063
    d0: -0.38599
    d1: 0.35310
    d2: -0.00151
    d3: 0.00432
    width: 1024
    height: 768
  camRight:
    fx: 861.59200
    fy: 864.90683
    cx: 532.82283
    cy: 393.51070
    d0: -0.33618
    d1: 0.20479
    d2: 0.00117
    d3: -0.00638
    width: 1024
    height: 768
  extrinsic:
    tx: 118.21890 #baseline in x (mm)
    ty: 0.00 #baseline in y (mm)
    tz: 0.00 #baseline in z (mm)
    rx: 0.00 #rotation along x (rad)
    ry: 0.00 #rotation along y (rad)
    rz: 0.00 #rotation along z (rad)



